[workspace]
members = [
    "natbreak/sniffer",
    "natbreak/breaker",
    "natbreak/test_async",
    "natbreak/sniffer-helper",
    "natbreak/objdump_observer"
]


#[profile.dev]
#split-debuginfo = "unpacked"
