[package]
name = "breaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sniffer = {path ="../sniffer", version = "0.1.0"}
borsh = "0.9.3"
crossbeam-channel = "0.5.6"