[package]
name = "test_async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
dashmap = "5.4.0"
rand = "0.8.5"
dhat = "0.3.1"
hashbrown = "0.12.3"