[package]
name = "sniffer-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.6"
borsh = "0.9.3"
lazy_static = "1.4.0"